-- ----------------------------
-- Table structure for small_sample_2
-- ----------------------------
DROP TABLE IF EXISTS `small_sample_2`;
CREATE TABLE `small_sample_2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `item_id` int(11) DEFAULT NULL,
  `serial` int(11) DEFAULT NULL,
  `label` int(11) DEFAULT NULL,
  `sj_title_1_1_n` int(11) DEFAULT '0',
  `sj_title_1_1_p` int(1) DEFAULT '0',
  `sj_title_2_1_n` int(11) DEFAULT '0',
  `sj_title_2_1_p` int(11) DEFAULT '0',
  `sj_title_2_2_n` int(11) DEFAULT '0',
  `sj_title_2_2_p` int(11) DEFAULT '0',
  `sj_tags_1_1_n` int(11) DEFAULT '0',
  `sj_tags_1_1_p` int(11) DEFAULT '0',
  `sj_tags_2_1_n` int(11) DEFAULT '0',
  `sj_tags_2_1_p` int(11) DEFAULT '0',
  `sj_tags_2_2_n` int(11) DEFAULT '0',
  `sj_tags_2_2_p` int(11) DEFAULT '0',
  `sj_geo_1_1_n` int(11) DEFAULT '0',
  `sj_geo_1_1_p` int(11) DEFAULT '0',
  `sj_geo_2_1_n` int(11) DEFAULT '0',
  `sj_geo_2_1_p` int(11) DEFAULT '0',
  `sj_geo_2_2_n` int(11) DEFAULT '0',
  `sj_geo_2_2_p` int(11) DEFAULT '0',
  `sj_dis_1_1_n` int(11) DEFAULT '0',
  `sj_dis_1_1_p` int(11) DEFAULT '0',
  `sj_dis_2_1_n` int(11) DEFAULT '0',
  `sj_dis_2_1_p` int(11) DEFAULT '0',
  `sj_dis_2_2_n` int(11) DEFAULT '0',
  `sj_dis_2_2_p` int(11) DEFAULT '0',
  `sj_cl_1_1_n` int(11) DEFAULT '0',
  `sj_cl_1_1_p` int(11) DEFAULT '0',
  `sj_cl_2_1_n` int(11) DEFAULT '0',
  `sj_cl_2_1_p` int(11) DEFAULT '0',
  `sj_cl_2_2_n` int(11) DEFAULT '0',
  `sj_cl_2_2_p` int(11) DEFAULT '0',
  `sj_emp_1_1_n` int(11) DEFAULT '0',
  `sj_emp_1_1_p` int(11) DEFAULT '0',
  `sj_emp_2_1_n` int(11) DEFAULT '0',
  `sj_emp_2_1_p` int(11) DEFAULT '0',
  `sj_emp_2_2_n` int(11) DEFAULT '0',
  `sj_Emp_2_2_p` int(11) DEFAULT '0',
  `usj_title_1_n` int(11) DEFAULT '0',
  `usj_title_1_p` int(11) DEFAULT '0',
  `usj_title_2_n` int(11) DEFAULT '0',
  `usj_title_2_p` int(11) DEFAULT '0',
  `usj_title_3_n` int(11) DEFAULT '0',
  `usj_title_3_p` int(11) DEFAULT '0',
  `usj_tags_1_n` int(11) DEFAULT '0',
  `usj_tags_1_p` int(11) DEFAULT '0',
  `usj_tags_2_n` int(11) DEFAULT '0',
  `usj_tags_2_p` int(11) DEFAULT '0',
  `usj_tags_3_n` int(11) DEFAULT '0',
  `usj_tags_3_p` int(11) DEFAULT '0',
  `usj_geo_1_n` int(11) DEFAULT '0',
  `usj_geo_1_p` int(11) DEFAULT '0',
  `usj_geo_2_n` int(11) DEFAULT '0',
  `usj_geo_2_p` int(11) DEFAULT '0',
  `usj_geo_3_n` int(11) DEFAULT '0',
  `usj_geo_3_p` int(11) DEFAULT '0',
  `usj_dis_1_n` int(11) DEFAULT '0',
  `usj_dis_1_p` int(11) DEFAULT '0',
  `usj_dis_2_n` int(11) DEFAULT '0',
  `usj_dis_2_p` int(11) DEFAULT '0',
  `usj_dis_3_n` int(11) DEFAULT '0',
  `usj_dis_3_p` int(11) DEFAULT '0',
  `usj_cl_1_n` int(11) DEFAULT '0',
  `usj_cl_1_p` int(11) DEFAULT '0',
  `usj_cl_2_n` int(11) DEFAULT '0',
  `usj_cl_2_p` int(11) DEFAULT '0',
  `usj_cl_3_n` int(11) DEFAULT '0',
  `usj_cl_3_p` int(11) DEFAULT '0',
  `usj_emp_1_n` int(11) DEFAULT '0',
  `usj_emp_1_p` int(11) DEFAULT '0',
  `usj_emp_2_n` int(11) DEFAULT '0',
  `usj_emp_2_p` int(11) DEFAULT '0',
  `usj_emp_3_n` int(11) DEFAULT '0',
  `usj_emp_3_p` int(11) DEFAULT '0',
  `jsu_jr_1_n` int(11) DEFAULT '0',
  `jsu_jr_1_p` int(11) DEFAULT '0',
  `jsu_jr_2_n` int(11) DEFAULT '0',
  `jsu_jr_2_p` int(11) DEFAULT '0',
  `jsu_jr_3_n` int(11) DEFAULT '0',
  `jsu_jr_3_p` int(11) DEFAULT '0',
  `jsu_f_1_n` int(11) DEFAULT '0',
  `jsu_f_1_p` int(11) DEFAULT '0',
  `jsu_f_2_n` int(11) DEFAULT '0',
  `jsu_f_2_p` int(11) DEFAULT '0',
  `jsu_f_3_n` int(11) DEFAULT '0',
  `jsu_f_3_p` int(11) DEFAULT '0',
  `jsu_d_1_n` int(11) DEFAULT '0',
  `jsu_d_1_p` int(11) DEFAULT '0',
  `jsu_d_2_n` int(11) DEFAULT '0',
  `jsu_d_2_p` int(11) DEFAULT '0',
  `jsu_d_3_n` int(11) DEFAULT '0',
  `jsu_d_3_p` int(11) DEFAULT '0',
  `jsu_cl_1_n` int(11) DEFAULT '0',
  `jsu_cl_1_p` int(11) DEFAULT '0',
  `jsu_cl_2_n` int(11) DEFAULT '0',
  `jsu_cl_2_p` int(11) DEFAULT '0',
  `jsu_cl_3_n` int(11) DEFAULT '0',
  `jsu_cl_3_p` int(11) DEFAULT '0',
  `jsu_dis_1_n` int(11) DEFAULT '0',
  `jsu_dis_1_p` int(11) DEFAULT '0',
  `jsu_dis_2_n` int(11) DEFAULT '0',
  `jsu_dis_2_p` int(11) DEFAULT '0',
  `jsu_dis_3_n` int(11) DEFAULT '0',
  `jsu_dis_3_p` int(11) DEFAULT '0',
  `jsu_y_1_n` int(11) DEFAULT '0',
  `jsu_y_1_p` int(11) DEFAULT '0',
  `jsu_y_2_n` int(11) DEFAULT '0',
  `jsu_y_2_p` int(11) DEFAULT '0',
  `jsu_y_3_n` int(11) DEFAULT '0',
  `jsu_y_3_p` int(11) DEFAULT '0',
  `u_jobroles` text,
  `u_career_level` int(11) DEFAULT NULL,
  `u_discipline_id` int(11) DEFAULT NULL,
  `u_industry_id` int(11) DEFAULT NULL,
  `u_country` varchar(20) DEFAULT NULL,
  `u_region` int(11) DEFAULT NULL,
  `u_experience_n_entries_class` tinyint(4) DEFAULT NULL,
  `u_experience_years_experience` tinyint(4) DEFAULT NULL,
  `u_experience_years_in_current` tinyint(4) DEFAULT NULL,
  `u_edu_degree` tinyint(4) DEFAULT NULL,
  `u_edu_fieldofstudies` varchar(255) DEFAULT NULL,
  `i_title` varchar(255) DEFAULT NULL,
  `i_career_level` int(11) DEFAULT NULL,
  `i_discipline_id` int(11) DEFAULT NULL,
  `i_industry_id` int(11) DEFAULT NULL,
  `i_country` varchar(20) DEFAULT NULL,
  `i_region` int(11) DEFAULT NULL,
  `i_latitude` double DEFAULT NULL,
  `i_longitude` double DEFAULT NULL,
  `i_employment` int(11) DEFAULT NULL,
  `i_tags` text,
  PRIMARY KEY (`id`),
  KEY `id` (`id`),
  KEY `user_id` (`user_id`,`item_id`),
  KEY `item_id` (`item_id`),
  KEY `serial` (`serial`),
  KEY `label` (`label`),
  KEY `u_career_level` (`u_career_level`),
  KEY `u_discipline_id` (`u_discipline_id`),
  KEY `u_industry_id` (`u_industry_id`),
  KEY `u_country` (`u_country`),
  KEY `u_region` (`u_region`),
  KEY `u_edu_degree` (`u_edu_degree`),
  KEY `u_edu_fieldofstudies` (`u_edu_fieldofstudies`),
  KEY `u_experience_n_entries_class` (`u_experience_n_entries_class`),
  KEY `u_experience_years_experience` (`u_experience_years_experience`),
  KEY `u_experience_years_in_current` (`u_experience_years_in_current`),
  KEY `i_career_level` (`i_career_level`),
  KEY `i_discipline_id` (`i_discipline_id`),
  KEY `i_industry_id` (`i_industry_id`),
  KEY `i_country` (`i_country`),
  KEY `i_region` (`i_region`),
  KEY `i_latitude` (`i_latitude`,`i_longitude`),
  KEY `i_employment` (`i_employment`),
  FULLTEXT KEY `u_jobroles` (`u_jobroles`),
  FULLTEXT KEY `i_title` (`i_title`),
  FULLTEXT KEY `i_tags` (`i_tags`)
) ENGINE=InnoDB AUTO_INCREMENT=17505049 DEFAULT CHARSET=utf8;
